project:
  type: website
  output-dir: _site

website:
  title: "DataMetricus"
  site-url: "https://datametricus.github.io"
  description: "Independent quantitative advisory in health metrics, actuarial modelling, and reproducible research."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: training.qmd
        text: Training
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
    html-math-method: katex
    grid:
      sidebar-width: 0px
      body-width: 1080px
      margin-width: 0px
