project:
  type: website
  resources:
    - google7af2f480fcbc996e.html
    - CNAME
  output-dir: _site

website:
  title: "DataMetricus"
  favicon: "assets/logo-transparent.png"
  site-url: "https://datametricus.com"
  description: "Independent quantitative advisory in health metrics, actuarial modelling, and reproducible research."
  google-analytics:
    tracking-id: "G-XGF1P33KPV"
  navbar:
    logo: "assets/logo-transparent.png"
    logo-alt: "DataMetricus logo"
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: training.qmd
        text: Training
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
    html-math-method: katex
    grid:
      sidebar-width: 0px
      body-width: 1080px
      margin-width: 0px
